api_platform:
    title: WR506 API
    version: 1.0.0
    graphql:
        enabled: true
        graphiql:
            enabled: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 30
        pagination_maximum_items_per_page: 1000
        pagination_client_enabled: true
        pagination_client_items_per_page: true
